server:
  port: 8082
spring:
  cloud:
    discovery:
      enabled: true
  application:
      name: company-service

  datasource:
    url: jdbc:postgresql://postgres-company:5432/companydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
