version: "3.8"

services:
  user-service:
    image: user-service:latest
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - app-network

  company-service:
    image: company-service:latest
    build: ./company-service
    ports:
      - "8082:8082"
    networks:
      - app-network

  gateway:
    image: gateway-service:latest
    build: ./gateway-service
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
