version: "3.8"

services:
  eureka-server:
    build: modules/eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  api-gateway:
    build: modules/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - microservices-net

  user-service:
    build: modules/user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:h2:mem:userdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_H2_CONSOLE_ENABLED: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
    networks:
      - microservices-net

  company-service:
    build: modules/company-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:h2:mem:companydb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_H2_CONSOLE_ENABLED: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
